#!/bin/env bash
##comment out lines by adding at least two `#' at the beginning
#SBATCH --job-name=G4_inverted
#SBATCH --account=silvestri
#SBATCH --partition=highmem-inf
#SBATCH --output=/home/peirone/%x.out
#SBATCH --error=/home/peirone/%x.err
#SBATCH --time=100-00:00:00
#SBATCH --mem=100000
#SBATCH --ntasks=8

cd /marisdata/peirone/EFTCosmoMC_gal/

export OMP_NUM_THREADS=1

mpirun -np 8 ./eftcosmomc cluster_run/parameter_files/G4_inverted.ini > chains/G4_inverted.log
