#!/bin/env bash
##comment out lines by adding at least two `#' at the beginning
#SBATCH --job-name=G5_inverted
#SBATCH --account=silvestri
#SBATCH --partition=highmem
#SBATCH --output=/home/peirone/%x.out
#SBATCH --error=/home/peirone/%x.err
#SBATCH --time=5-00:00:00
#SBATCH --mem=100000
#SBATCH --ntasks=8

cd /marisdata/peirone/EFTCosmoMC_gal5/

export OMP_NUM_THREADS=1

mpirun -np 4 ./eftcosmomc cluster_run/parameter_files/G5_inverted.ini > chains/G5_inverted.log
