#!/bin/env bash
##comment out lines by adding at least two `#' at the beginning
#SBATCH --job-name=Ln_PB
#SBATCH --account=silvestri
#SBATCH --partition=highmem-inf
#SBATCH --output=/home/peirone/%x.out
#SBATCH --error=/home/peirone/%x.err
#SBATCH --time=100-00:00:00
#SBATCH --mem=10000
#SBATCH --ntasks=4

cd /marisdata/peirone/EFTCosmoMC_G3/

mpirun -np 8 ./eftcosmomc cluster_run/parameter_files/Planck_BAO/LCDM_normal.ini > chains/LCDM_normal_Planck_BAO.log
